language: ruby

rvm:
  - 2.6.3

cache: bundler

sudo: false

env:
  - RAILS_ENV=test

matrix:
  fast_finish: true

before_install:
  - gem update --system 3.0.3
  - gem install bundler -v 2.0.2
  - bundler install

script:
  - export RAILS_ENV=test
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rspec

notifications:
  email:
    recipients:
      - b.g.dariush@gmail.com
